POST http://localhost:3000/api/toto
Content-Type: application/json

{
    "data": {
        "name": "melissa"
        }
}
###
GET http://localhost:3000/api/toto/

###
GET http://localhost:3000/api/qcm/
 
###
POST http://localhost:3000/api/qcm
Content-Type: application/json

{
    "data": {
        "titre": "QCM sur l'Histoire",
        "imageSrc": null
    }
}

###
POST http://localhost:3000/api/qcm/1/questions
Content-Type: application/json

{
    "data": {
        "content": "Quelle est la capitale la plus haute du monde ?",
        "choices": [
            { "content": "Quito", "isCorrect": false },
            { "content": "La Paz", "isCorrect": true },
            { "content": "Katmandou", "isCorrect": false },
            { "content": "Bogotá", "isCorrect": false }
        ]
    }
}

###
POST http://localhost:3000/api/qcm/2/questions
Content-Type: application/json

{
    "data": {
        "content": "Quelle(s) invention(s) est/sont attribuée(s) à Gutenberg ?",
        "choices": [
            { "content": "L'imprimerie à caractères mobiles", "isCorrect": true },
            { "content": "La presse typographique", "isCorrect": true },
            { "content": "La machine à vapeur", "isCorrect": false },
            { "content": "La boussole", "isCorrect": false }
        ]
    }
}